bluetoothinfo: watch is optional

diff --git a/scripts/bluetoothinfo b/scripts/bluetoothinfo
--- a/scripts/bluetoothinfo
+++ b/scripts/bluetoothinfo
@@ -38,6 +38,18 @@ get_devices() {
 
 # main:
 
+arg="$1"
+if test -z $arg; then
+    watch=false
+elif [[ "$arg" =~ ^wa?t?c?h? ]]; then
+    watch=true
+else
+    echo "Invalid argument '$1'. Usage:" 1>&2
+    echo "    (no arg) -> print info once" 1>&2
+    echo "    w[atch]  -> update device info ever second" 1>&2
+    exit 1
+fi
+
 echo "# local controllers:"
 bluetoothctl list
 
@@ -53,5 +65,6 @@ while true; do
     remove_last_lines $lines
     ((lines=$(wc -l <<< "$text")))
     echo "$text"
+    if ! $watch; then break; fi
     sleep 1
 done
